### ISSUE TITLE
[bug] Re-use central point as initial guess for displacements in Hessian calculation

### ISSUE THREAD

**Issue by erbas** [mtzgroup/tccloud#26]
The Hessian and frequency calculations can give incorrect results, as discussed in summer school. It needs to be run as a single point at the given geometry. Then the calculations are displaced geometries can be run in parallel, using the wave function from the central point as the initial guess for those calculations.

**Comment by coltonbh** [comment]
Wavefunction can now be passed as initial guess to distributed algorithms. See [PR51](https://github.com/mtzgroup/terachem-cloud/pull/51) and bugfix [PR52](https://github.com/mtzgroup/terachem-cloud/pull/52)
