### ISSUE TITLE
More graceful handling of terachem failures

### ISSUE THREAD

**Issue by erbas** [mtzgroup/tccloud#27]
It is quite common for a TeraChem calculation to fail. The TCCloud API needs to provide the user with more helpful information than HTTP 500, so they can do something about modifying their input.

**Comment by coltonbh** [comment]
You are looking for a property on an object that does not exist. This is not a terachem failure. This is user error ;)

Before trying to access a return result, ensure your computation was successful:
```
if result.success:
    # access your return result, do whatever
else:
    # handle your failed operation.
```

Note this pattern is covered in the docs here: https://mtzgroup.github.io/tccloud/tutorial/geometry_optimization/

Would be nice to add to the `Compute` docs section too.

**Comment by coltonbh** [comment]
You'll note the API returned a object for you to work with, the FailedOperation object (as per the last line of your stack trace). Check docs to see how to understand your failure. These are not 500 errors.

https://mtzgroup.github.io/tccloud/code_reference/FailedOperation/

**Comment by coltonbh** [comment]
Since TeraChem does not return log files via the TCPB interface expect this feature to be some time off, as it would require changes at the TeraChem level, then the TCPB interface level. I agree it would be great to have 👍 If you have experience at this level of TeraChem and can add the ability for the TCPB interface to speak TeraChem log files I'll gladly add it to TCC once complete.

**Comment by coltonbh** [comment]
A short term hack I use, since TeraChem doesn't speak log files, is to send the same computation to psi4 and get the full log file back for diagnostics. Not ideal, but an option.

**Comment by erbas** [comment]
The old API and client did this. I think the API server was grabbing the last 100 lines of the log file, using the path information that the TCPB server returned.

psi4 output will be irrelevant for understanding why terachem crashed
